In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [3]:
arr2 = np.array([5, 6, 7], dtype = float)
arr2.dtype

dtype('float64')

In [12]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])

In [13]:
a + b

array([15, 23, 14,  8])

In [14]:
a * 2

array([20, 16, 10,  2])

In [10]:
matrixA = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
matrixA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
matrixB = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9')
matrixB

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
np.shape(matrixA)

(3, 3)

In [11]:
matrixA[2, 1]

8

In [12]:
matrixA + matrixB

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [14]:
matrixB * 5

matrix([[ 5, 10, 15],
        [20, 25, 30],
        [35, 40, 45]])

In [15]:
# transposition
# [1, 2, 3], |>> | [1, 4, 7],
# [4, 5, 6], |>> | [2, 5, 8],
# [7, 8, 9]  |>> | [3, 6, 9]
matrixB.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [17]:
matrixA * matrixB

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [18]:
A_1 = np.matrix("1,-5;2,2;0,3")
A_2 = np.matrix("3,1,0;-1,0,2")

In [19]:
A_1

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [20]:
A_2

matrix([[ 3,  1,  0],
        [-1,  0,  2]])