In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4])

In [5]:
np.sum(arr)  # 1 + 2 + 3 + 4 = 10

10

In [17]:
arr.sum()

10

In [8]:
np.abs(-2)  #|2| модуль

2

In [10]:
np.prod(arr)  # 1 * 2 * 3 * 4 = 24

24

In [11]:
np.sqrt(arr)  # квадратный корень

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [13]:
ar = np.array([4.5, 1.2])
np.modf(ar)  # Дробные и целые части массива в виде отдельных массивов

(array([0.5, 0.2]), array([4., 1.]))

In [14]:
# Массив логических (булевых) значений, показывающий, какие из элементов исходного массива являются NaN (не числами)
np.isnan(arr)

array([False, False, False, False])